/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp11_java_App */

#ifndef _Included_cpp11_java_App
#define _Included_cpp11_java_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp11_java_App
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cpp11_java_App_print
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_cpp11_java_App_getLine
  (JNIEnv *env, jobject object, jstring promt);

JNIEXPORT jint JNICALL Java_cpp11_java_App_sumArray
  (JNIEnv *env, jobject object, jintArray arr);

JNIEXPORT jobjectArray JNICALL Java_cpp11_java_App_initInt2DArray
  (JNIEnv *env, jobject object, jint size);

JNIEXPORT void JNICALL Java_cpp11_java_App_accessField
  (JNIEnv *env, jobject object);

JNIEXPORT void JNICALL Java_cpp11_java_App_nativeMethod
  (JNIEnv *env, jobject object);



#ifdef __cplusplus
}

#endif
#endif
